Populate and remove todos based on selected date
4l3x-suvnet/todo_calendar pull request #111
Opened 2022-06-17 16:33 UTC by Annangggg

close #110

2022-06-17 16:55 UTC, 4l3x-suvnet requested changes
Isn't this already done?

2022-06-18 02:16 UTC, Serover commented on js/todos.js
> +  console.log("aaaa");
mby remove this log

2022-06-18 02:17 UTC, Serover approved these changes

2022-06-18 10:21 UTC, 4l3x-suvnet approved these changes
Works great!

2022-06-18 10:22 UTC, merged