44 add images folder
4l3x-suvnet/todo_calendar pull request #48
Opened 2022-06-10 13:59 UTC by Annangggg

close #44

2022-06-10 14:06 UTC, pollyyllop commented
@Annangggg It has to be an PNG. On a PNG there's a chess board pattern behind the image. Like gray and white squares as the image background. If it's not a PNG the background of the image will hide text behind it if there's any nearby the image.

2022-06-10 14:06 UTC, pollyyllop requested changes
@Annangggg It has to be an PNG. On a PNG there's a chess board pattern behind the image. Like gray and white squares as the image background. If it's not a PNG the background of the image will hide text behind it if there's any nearby the image.

2022-06-12 17:13 UTC, pollyyllop approved these changes
There we go!

2022-06-13 11:49 UTC, Serover approved these changes

2022-06-13 11:49 UTC, merged